"""auto_phone_column

Revision ID: 87dd944f1276
Revises: cf8ab4c5762a
Create Date: 2024-06-07 23:19:01.981165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dd944f1276'
down_revision: Union[str, None] = 'cf8ab4c5762a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_no')
    # ### end Alembic commands ###
